#include "IniReader.h"
#include "Macros.h"
#include <stdlib.h>
#include <assert.h>
#include <math.h>

using namespace std;

// these are the values that are extern'd in SystemConfig.h so that they
// have global scope even though they are set by IniReader
namespace LPDDRSim {
uint64_t TOTAL_STORAGE;
std::string DDR_TYPE;
std::string DDR_MODE;
unsigned DMC_RATE;
std::string DRAM_VENDOR;
std::string DRAM_MODE;
bool IS_LP4;
bool IS_LP5;
bool IS_LP6;
bool IS_GD1;
bool IS_GD2;
bool IS_G3D;
bool IS_DDR4;
bool IS_DDR5;
bool IS_HBM2E;
bool IS_HBM3;
unsigned NUM_SIDS;
unsigned NUM_GROUPS;
unsigned NUM_RANKS;
unsigned NUM_BANKS;
unsigned NUM_CHANS;
unsigned NUM_ROWS;
unsigned NUM_COLS;
unsigned NUM_MATGRPS;
unsigned DRAM_CAPACITY;
unsigned JEDEC_DATA_BUS_BITS;
unsigned DMC_DATA_BUS_BITS;
bool FASTWAKEUP_EN;
bool PREDICT_FASTWAKEUP;
bool QOS_INV;
bool GREEN_PATH_DIS;
bool LQOS_BP_EN;
unsigned LQOS_BP_LEVEL;
bool TIMEOUT_ENABLE;
unsigned QOS_POLICY;
unsigned TIMEOUT_MODE;
unsigned RDATA_TYPE;

unsigned tREFI;
float PAM_RATIO;
float tDFI;
float Vdd;
unsigned RL;
unsigned WL;
unsigned BLEN;
std::vector <unsigned> BL;
unsigned tRAS;
unsigned tRCD_WR;
unsigned tRCD;
unsigned tRRD_L;
unsigned tRRD_S;
unsigned tRPpb;
unsigned tRPab;
unsigned tRPfg;
unsigned tPPD;
unsigned tPPD_L;
unsigned tFPW;
unsigned tCCD_L;
unsigned tCCD_R;
unsigned tCCD_M;
unsigned tCCD_M_WR;
unsigned tCCD_L_WR;
unsigned tCCD_L_WR2;
unsigned tCCD_NSR;
unsigned tCCD_NSW;
unsigned tCCD_S;
unsigned tCCDMW;
unsigned tCCD_L24;
unsigned tCCD_L48;
unsigned PCFG_TWR;
unsigned PCFG_TRTP;
unsigned PCFG_TRTW;
unsigned PCFG_TRTW_L;
unsigned PCFG_TWTR;
unsigned PCFG_TWTR_L;
unsigned PCFG_TWTR_SB;
unsigned PCFG_RANKTRTR;
unsigned PCFG_RANKTRTW;
unsigned PCFG_RANKTWTR;
unsigned PCFG_RANKTWTW;
unsigned tRFCab;
unsigned tFAW;
unsigned tPIPE_PRE_DMC;
unsigned tCMD_PHY;
unsigned tCMD_RASC;
unsigned tCMD_ADAPT;
unsigned tWDATA_DMC;
unsigned tDAT_PHY;
unsigned tDAT_RASC;
unsigned tCMD2SCH;
unsigned tCMD2SCH_BYPACT;
unsigned tCMD_CONF;
unsigned tD_D;
unsigned tRFCpb;
unsigned tPBR2PBR;
unsigned tPBR2PBR_L;
unsigned tPBR2ACT;
unsigned tCMD_WAKEUP;
unsigned tXP;
unsigned tXP_V570;
unsigned tXP_V580;
unsigned tXP_V590;
unsigned tXSR;
unsigned tCMDPD;
unsigned tnACU;
unsigned tRDPD;
unsigned tRDAPPD;
unsigned tWRPD;
unsigned tWRAPPD;
unsigned tPDE;
unsigned tCSPD;
unsigned tPDLP;
unsigned tPHYLPE;
unsigned tPHYLPX;
unsigned tASREFE;
unsigned ABR_PSTPND_LEVEL;
unsigned PBR_PSTPND_LEVEL;
unsigned PRE_NUM_SEND_PBR;
bool IECC_ENABLE;
unsigned PDU_DEPTH;
unsigned IECC_CONFLICT_CNT;
bool PD_ENABLE;
bool ASREF_ENABLE;
bool ASREF_ADAPT_EN;
bool IECC_PARTIAL_BYPASS;
uint64_t IECC_BYPASS_ADDRESS;
bool IECC_BL32_MODE;
unsigned IECC_PRI;
unsigned IECC_CAP_RATIO;

float POWER_RDINC_K;
float POWER_RDWRAP_K;
float POWER_WRINC_K;
float POWER_WRWRAP_K;
float POWER_RDATA_K;
float POWER_WDATA_K;
float POWER_ACT_K;
float POWER_PREP_K;
float POWER_PRES_K;
float POWER_PREA_K;
std::vector <float> POWER_RD_K;
std::vector <float> POWER_WR_K;
std::vector <float> POWER_QUEUE_K;
float POWER_PBR_K;
float POWER_ABR_K;
float POWER_R2W_K;
float POWER_W2R_K;
float POWER_RNKSW_K;
float POWER_PDE_K;
float POWER_ASREFE_K;
float POWER_SRPDE_K;
float POWER_PDX_K;
float POWER_ASREFX_K;
float POWER_SRPDX_K;
float POWER_IDLE_K;
float POWER_PDCC_K;
uint64_t MATRIX_ROW23;
uint64_t MATRIX_ROW22;
uint64_t MATRIX_ROW21;
uint64_t MATRIX_ROW20;
uint64_t MATRIX_ROW19;
uint64_t MATRIX_ROW18;
uint64_t MATRIX_ROW17;
uint64_t MATRIX_ROW16;
uint64_t MATRIX_ROW15;
uint64_t MATRIX_ROW14;
uint64_t MATRIX_ROW13;
uint64_t MATRIX_ROW12;
uint64_t MATRIX_ROW11;
uint64_t MATRIX_ROW10;
uint64_t MATRIX_ROW9;
uint64_t MATRIX_ROW8;
uint64_t MATRIX_ROW7;
uint64_t MATRIX_ROW6;
uint64_t MATRIX_ROW5;
uint64_t MATRIX_ROW4;
uint64_t MATRIX_ROW3;
uint64_t MATRIX_ROW2;
uint64_t MATRIX_ROW1;
uint64_t MATRIX_ROW0;
uint64_t MATRIX_CH;
uint64_t MATRIX_RA2;
uint64_t MATRIX_RA1;
uint64_t MATRIX_RA0;
uint64_t MATRIX_BA6;
uint64_t MATRIX_BA5;
uint64_t MATRIX_BA4;
uint64_t MATRIX_BA3;
uint64_t MATRIX_BA2;
uint64_t MATRIX_BA1;
uint64_t MATRIX_BA0;
uint64_t MATRIX_BG4;
uint64_t MATRIX_BG3;
uint64_t MATRIX_BG2;
uint64_t MATRIX_BG1;
uint64_t MATRIX_BG0;
uint64_t MATRIX_SID2;
uint64_t MATRIX_SID1;
uint64_t MATRIX_SID0;
uint64_t MATRIX_COL10;
uint64_t MATRIX_COL9;
uint64_t MATRIX_COL8;
uint64_t MATRIX_COL7;
uint64_t MATRIX_COL6;
uint64_t MATRIX_COL5;
uint64_t MATRIX_COL4;
uint64_t MATRIX_COL3;
uint64_t MATRIX_COL2;
uint64_t MATRIX_COL1;
uint64_t MATRIX_COL0;

bool DEBUG_STATE;
bool DEBUG_GBUF_STATE;
bool DEBUG_RMW_STATE;
bool DEBUG_PDU;
bool ECC_MERGE_ENABLE;
uint64_t DEBUG_START_TIME;
uint64_t DEBUG_END_TIME;
unsigned FLOW_STAT_TIME;
unsigned DMC_THEORY_BW;
bool MPAM_PUSH_EN;
bool MID_PUSH_EN;
unsigned PD_PRD;
unsigned ASREF_PRD;
unsigned ASREF_ADAPT_WIN;

//Memory Controller related parameters
unsigned TRANS_QUEUE_DEPTH;
unsigned TABLE_DEPTH;
//row accesses allowed before closing (open page)
// strings and their associated enums

float WCK2DFI_RATIO;
bool OFREQ_EN;
float OFREQ_RATIO;
unsigned tDIM_R_R;
unsigned tDIM_W_W;
bool BUSYSTATE_INC_WCMD;
unsigned BUSYSTATE_TH;
bool DEBUG_BUS;
bool RD_APRE_EN;
bool WR_APRE_EN;
bool ENHAN_RD_AP_EN;
bool ENHAN_WR_AP_EN;
bool AREF_EN;
bool PBR_EN;
bool ENH_PBR_EN;
bool ENH_PBR_CEIL_EN;
bool DERATING_EN;
unsigned DERATING_RATIO;
bool PBR_PARA_EN;
bool AREF_OFFSET_EN;
bool SBR_IDLE_EN;
unsigned SBR_REQ_MODE;
unsigned SBR_FRCST_NUM;
unsigned SBR_WEIGHT_MODE;
unsigned SBR_WEIGHT_ENH_MODE;
unsigned SBR_GAP_CNT;
bool SBR_IDLE_ADAPT_EN;
unsigned SBR_IDLE_ADAPT_WIN;
unsigned SBR_IDLE_ADAPT_LEVEL;
bool SEND_DSTREF_SERIAL;
bool PD_PBR_EN;
unsigned FG_REFRESH_TH;
std::string SYSTEM_CONFIG;
bool STATE_LOG;
bool PRINT_TRACE;
bool PRINT_READ;
bool PRINT_RDATA;
bool PRINT_SCH;
bool PRINT_EXEC;
bool PRINT_IDLE_LAT;
bool PRINT_LATENCY;
bool PRINT_DRAM_TRACE;
bool PRINT_UT_TRACE;
bool PRINT_CMD_NUM;
uint64_t PRINT_CH_OHOT;
bool PRINT_BW;
uint32_t PRINT_BW_WIN;
bool PERFECT_DMC_EN;
unsigned PERFECT_DMC_DELAY;
bool DROP_WRITE_CMD;
bool LAT_INC_BP;
bool FORCE_BAINTLV_EN;
bool POWER_EN;
bool BA_SHIFT_DIR;
unsigned BA_SHIFT_BIT;
bool SLOT_FIFO;
bool TIME_ASSERT_EN;
unsigned EXEC_NUMBER;
std::vector <unsigned> TIMEOUT_PRI_RD;
std::vector <unsigned> TIMEOUT_PRI_WR;
bool PRI_ADPT_ENABLE;
std::vector <unsigned> ADAPT_PRI_RD;
std::vector <unsigned> ADAPT_PRI_WR;
std::vector <unsigned> ASREF_ADAPT_LEVEL;
std::vector <unsigned> ASREF_ADAPT_PRD;
bool MPAM_MAPPING_TIMEOUT;
#ifdef SYSARCH_PLATFORM
std::map <std::string, std::vector<int64_t>> MAP_CONFIG;
#else
std::map <std::string, std::vector<unsigned>> MAP_CONFIG;
#endif
std::vector <unsigned> MPAM_TIMEOUT_RD;
std::vector <unsigned> MPAM_TIMEOUT_WR;
std::vector <unsigned> MPAM_ADAPT_RD;
std::vector <unsigned> MPAM_ADAPT_WR;
bool PRIORITY_PASS_ENABLE;
bool DEBUG_INI_READER=false;
unsigned STATE_TIME;
bool PAGE_ADAPT_EN;
bool PAGE_TIMEOUT_EN;
unsigned OPENPAGE_TIME_RD;
unsigned OPENPAGE_TIME_WR;
bool ENH_PAGE_ADPT_EN;
unsigned ENH_PAGE_ADPT_WIN;
std::vector <unsigned> ENH_PAGE_ADPT_LVL;
std::vector <unsigned> ENH_PAGE_ADPT_TIME;
unsigned DMC_BW_WIN;
std::vector <unsigned> DMC_BW_LEVEL;
bool PAGE_ADPT_EN;
unsigned PAGE_WIN_MODE;
unsigned PAGE_WIN_SIZE;
unsigned PAGE_OPC_TH;
unsigned PAGE_PPC_TH;
unsigned PAGE_ADPT_STEP;
unsigned PAGE_TIME_MAX;
unsigned DRESP_BP_TH; 
bool GRP_RW_EN;
unsigned ENGRP_LEVEL;
unsigned EXGRP_LEVEL;
unsigned CMD_WLEVELL;
unsigned CMD_WLEVELH;
unsigned SERIAL_RLEVELL;
unsigned SERIAL_RLEVELH;
unsigned SERIAL_WLEVELL;
unsigned SERIAL_WLEVELH;
unsigned RLEVEL_R2W;
unsigned ALEVEL_W2R;
bool HARDWARE_RHIT_EN;
unsigned CMD_RLEVELL;
unsigned CMD_RLEVELH;
unsigned RHIT_RW_CMD_NUM;
unsigned RHIT_ACT_CMD_NUM;
bool RWGRP_TRANS_BY_TOUT;
unsigned RWGRP_AUTO_BW;
bool GRP_RANK_EN;
unsigned GRP_RANK_MODE;
bool GRP_RANK_PREPB;
bool GRP_RANK_PREAB;
unsigned GRP_RANK_LEVEL;
bool SIMPLE_GRP_RANK_EN;
unsigned READ_RANK_GRP_LEVEL0_H;
unsigned READ_RANK_GRP_LEVEL0_L;
unsigned READ_RANK_GRP_LEVEL1_H;
unsigned READ_RANK_GRP_LEVEL1_L;
bool SIMPLE_GRP_SID_EN;
std::vector <unsigned> GRP_SID_LEVEL;
bool RCMD_HQOS_EN;
unsigned RCMD_HQOS_LEVEL;
unsigned SWITCH_HQOS_LEVEL;
unsigned CPU_MID_START;
unsigned CPU_MID_END;
bool RCMD_HQOS_W2R_SWITCH_EN;
unsigned RCMD_HQOS_W2R_RLEVELH;
unsigned RCMD_HQOS_RANK_SWITCH_LEVELH;
unsigned RCMD_HQOS_RANK_SWITCH_LEVELL;
unsigned RCMD_HQOS_RANK_SWITCH_ROWHIT_LEVEL;
bool RCMD_HQOS_RANK_SWITCH_EN;
bool RHIT_HQOS_BREAK_EN;
unsigned RHIT_HQOS_BREAK_OTH_RCMD_LEVEL;
bool BYP_ACT_EN;
bool RHIT_BREAK_EN;
unsigned RHIT_BREAK_LEVEL;
unsigned RW_GRPCHG_W2R_TH;
unsigned RW_GRPCHG_R2W_TH;
bool DMC_V580;
bool DMC_V590;
bool DMC_V596;
bool EARLY_TCCDL_EN;
bool TRFC_CC_EN;
unsigned WB_WDEPTH;
unsigned WB_RDEPTH;
bool MERGE_ENABLE;
bool FORWARD_ENABLE;
bool DYN_BYP_EN;
bool GBUF_RCMD_BLOCK_PBR;
bool GBUF_RD_BRK_WFLUSH_CMD;
unsigned GBUF_RCMD_TIMEOUT;
unsigned GBUF_WCMD_PRIADAPT;
bool RQ_RNKCONF_EN;
bool RQ_ADCONF_PUSH_EN;
unsigned CMD_ROW_ORDER;
unsigned TOTAL_RCMD_MODE;
unsigned RQ_BACONF_MODE;
unsigned WQ_BACONF_MODE;
bool RO_HIT_EN;
std::vector <unsigned> GRP_MODE_LEVEL0;
std::vector <unsigned> GRP_MODE_LEVEL1;
std::vector <unsigned> GRP_MODE_LEVEL2;
std::vector <unsigned> GRP_MODE_LEVEL3;
std::vector <unsigned> BANK_CMD_TH;
std::vector <unsigned> NO_CMD_SCH_TH;
std::vector <unsigned> WGRP_RANK_MODE;
std::vector <unsigned> WR_LEVEL0;
std::vector <unsigned> WR_LEVEL1;
std::vector <unsigned> WR_LEVEL2;
std::vector <unsigned> WR_LEVEL3;
std::vector <unsigned> WR_MOST_LEVEL0;
std::vector <unsigned> WR_MOST_LEVEL1;
std::vector <unsigned> WR_MOST_LEVEL2;
std::vector <unsigned> WR_MOST_LEVEL3;
std::vector <unsigned> RD_LEVEL0;
std::vector <unsigned> RD_LEVEL1;
std::vector <unsigned> RD_LEVEL2;
std::vector <unsigned> RD_LEVEL3;
bool WRITE_BUFFER_ENABLE;
bool EM_ENABLE;
unsigned EM_MODE;
bool RMW_ENABLE;
unsigned RMW_CMD_MODE;
unsigned RMW_QUE_DEPTH;
unsigned RMW_CONF_SIZE;
unsigned GRT_FIFO_DEPTH;
unsigned TRANS_FIFO_DEPTH;
unsigned ROW_SEL;
bool BG_ROTATE_EN;
bool RCMD_BANK_ARB_EN;
bool WCMD_BANK_ARB_EN;
unsigned RCMD_BANK_ARB_PRI;
unsigned WCMD_BANK_ARB_PRI;
bool WCK_ALWAYS_ON;
bool CAS_FS_EN;
unsigned CAS_FS_TH;
unsigned CORE_CONCURR;
unsigned CORE_CONCURR_PRD;
bool WCMD_MERGE_EN;
unsigned WRITE_MERGE_BUFFER_DEPTH;
bool UNPAIRED_TO_RMW_EN;

bool DRAM_POWER_EN;
float IDD01, IDD02H, IDD02L, IDD0Q;
float IDD2P1, IDD2P2H, IDD2P2L, IDD2PQ, IDD2PS1, IDD2PS2H, IDD2PS2L, IDD2PSQ;
float IDD2N1, IDD2N2H, IDD2N2L, IDD2NQ, IDD2NS1, IDD2NS2H, IDD2NS2L, IDD2NSQ;
float IDD3P1, IDD3P2H, IDD3P2L, IDD3PQ, IDD3PS1, IDD3PS2H, IDD3PS2L, IDD3PSQ;
float IDD3N1, IDD3N2H, IDD3N2L, IDD3NQ, IDD3NS1, IDD3NS2H, IDD3NS2L, IDD3NSQ;
float IDD4R1_BG, IDD4R2H_BG, IDD4R2L_BG, IDD4RQ_BG, IDD4R1_BK, IDD4R2H_BK, IDD4R2L_BK, IDD4RQ_BK;
float IDD4W1_BG, IDD4W2H_BG, IDD4W2L_BG, IDD4WQ_BG, IDD4W1_BK, IDD4W2H_BK, IDD4W2L_BK, IDD4WQ_BK;
float IDD51, IDD52H, IDD52L, IDD5Q, IDD5AB1, IDD5AB2H;
float IDD5AB2L, IDD5ABQ, IDD5PB1, IDD5PB2H, IDD5PB2L, IDD5PBQ;
float IDD61, IDD62H, IDD62L, IDD6Q, IDD6DS1, IDD6DS2H, IDD6DS2L, IDD6DSQ;
float VDD1, VDD2H, VDD2L, VDDQH, VDDQL;

SchedulingPolicy schedulingPolicy;
BankTableMappingPolicy BankTableMode;
QueuingStructure queuingStructure;

//Map the string names to the variables they set
static ConfigMap configMap[] = {
    //DEFINE_UINT_PARAM -- see IniReader.h
    DEFINE_FLOAT_PARAM(WCK2DFI_RATIO,DEV_PARAM),
    DEFINE_BOOL_PARAM(OFREQ_EN,DEV_PARAM),
    DEFINE_FLOAT_PARAM(OFREQ_RATIO,DEV_PARAM),
    DEFINE_UINT_PARAM(JEDEC_DATA_BUS_BITS,DEV_PARAM),
    DEFINE_UINT_PARAM(DMC_DATA_BUS_BITS,DEV_PARAM),
    DEFINE_UINT_PARAM(tREFI,DEV_PARAM),
    DEFINE_FLOAT_PARAM(PAM_RATIO,DEV_PARAM),
    DEFINE_FLOAT_PARAM(tDFI,DEV_PARAM),
    DEFINE_UINT_PARAM(WL,DEV_PARAM),
    DEFINE_UINT_PARAM(RL,DEV_PARAM),
    DEFINE_UINTARRAY_PARAM(BL,DEV_PARAM),
    DEFINE_UINT_PARAM(tRAS,DEV_PARAM),
    DEFINE_UINT_PARAM(tRCD_WR,DEV_PARAM),
    DEFINE_UINT_PARAM(tRCD,DEV_PARAM),
    DEFINE_UINT_PARAM(tRRD_S,DEV_PARAM),
    DEFINE_UINT_PARAM(tRRD_L,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCDMW,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_L24,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_L48,DEV_PARAM),
    DEFINE_UINT_PARAM(tRPpb,DEV_PARAM),
    DEFINE_UINT_PARAM(tRPab,DEV_PARAM),
    DEFINE_UINT_PARAM(tRPfg,DEV_PARAM),
    DEFINE_UINT_PARAM(tPPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tPPD_L,DEV_PARAM),
    DEFINE_UINT_PARAM(tFPW,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_S,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_L,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_R,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_M,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_M_WR,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_L_WR,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_L_WR2,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_NSR,DEV_PARAM),
    DEFINE_UINT_PARAM(tCCD_NSW,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TWR,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TRTP,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TRTW,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TRTW_L,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TWTR,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TWTR_L,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_TWTR_SB,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_RANKTRTR,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_RANKTRTW,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_RANKTWTR,DEV_PARAM),
    DEFINE_UINT_PARAM(PCFG_RANKTWTW,DEV_PARAM),
    DEFINE_UINT_PARAM(tRFCab,DEV_PARAM),
    DEFINE_UINT_PARAM(tFAW,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD_WAKEUP,DEV_PARAM),
    DEFINE_UINT_PARAM(tXP_V570,DEV_PARAM),
    DEFINE_UINT_PARAM(tXP_V580,DEV_PARAM),
    DEFINE_UINT_PARAM(tXP_V590,DEV_PARAM),
    DEFINE_UINT_PARAM(tXSR,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMDPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tnACU,DEV_PARAM),
    DEFINE_UINT_PARAM(tRDPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tRDAPPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tWRPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tWRAPPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tPDE,DEV_PARAM),
    DEFINE_UINT_PARAM(tCSPD,DEV_PARAM),
    DEFINE_UINT_PARAM(tPDLP,DEV_PARAM),
    DEFINE_UINT_PARAM(tPHYLPE,DEV_PARAM),
    DEFINE_UINT_PARAM(tPHYLPX,DEV_PARAM),
    DEFINE_UINT_PARAM(tASREFE,DEV_PARAM),
    DEFINE_BOOL_PARAM(BUSYSTATE_INC_WCMD,SYS_PARAM),
    DEFINE_UINT_PARAM(BUSYSTATE_TH,SYS_PARAM),
    DEFINE_BOOL_PARAM(IECC_ENABLE,SYS_PARAM),
    DEFINE_UINT_PARAM(PDU_DEPTH,SYS_PARAM),
    DEFINE_UINT_PARAM(IECC_CONFLICT_CNT,SYS_PARAM),
    DEFINE_BOOL_PARAM(IECC_PARTIAL_BYPASS,SYS_PARAM),
    DEFINE_UINT64HEX_PARAM(IECC_BYPASS_ADDRESS,SYS_PARAM),
    DEFINE_BOOL_PARAM(IECC_BL32_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(IECC_PRI,SYS_PARAM),
    DEFINE_UINT_PARAM(IECC_CAP_RATIO,SYS_PARAM),

    DEFINE_BOOL_PARAM(PD_ENABLE,SYS_PARAM),
    DEFINE_UINT_PARAM(PD_PRD,SYS_PARAM),
    DEFINE_BOOL_PARAM(ASREF_ENABLE,SYS_PARAM),
    DEFINE_BOOL_PARAM(ASREF_ADAPT_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(ASREF_PRD,SYS_PARAM),
    DEFINE_UINT_PARAM(ASREF_ADAPT_WIN,SYS_PARAM),
    DEFINE_UINT_PARAM(DMC_THEORY_BW,SYS_PARAM),
    DEFINE_UINT_PARAM(FLOW_STAT_TIME,SYS_PARAM),
    DEFINE_BOOL_PARAM(MPAM_PUSH_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(MID_PUSH_EN,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(ASREF_ADAPT_LEVEL,DEV_PARAM),
    DEFINE_UINTARRAY_PARAM(ASREF_ADAPT_PRD,DEV_PARAM),

    DEFINE_BOOL_PARAM(DEBUG_STATE,SYS_PARAM),
    DEFINE_BOOL_PARAM(DEBUG_GBUF_STATE,SYS_PARAM),
    DEFINE_BOOL_PARAM(DEBUG_RMW_STATE,SYS_PARAM),
    DEFINE_BOOL_PARAM(DEBUG_PDU,SYS_PARAM),
    DEFINE_BOOL_PARAM(ECC_MERGE_ENABLE,SYS_PARAM),
    DEFINE_UINT64_PARAM(DEBUG_START_TIME,SYS_PARAM),
    DEFINE_UINT64_PARAM(DEBUG_END_TIME,SYS_PARAM),
    DEFINE_UINT_PARAM(tPIPE_PRE_DMC,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD_PHY,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD_ADAPT,DEV_PARAM),
    DEFINE_UINT_PARAM(tWDATA_DMC,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD_RASC,DEV_PARAM),
    DEFINE_UINT_PARAM(tDAT_PHY,DEV_PARAM),
    DEFINE_UINT_PARAM(tDAT_RASC,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD2SCH,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD2SCH_BYPACT,DEV_PARAM),
    DEFINE_UINT_PARAM(tCMD_CONF,DEV_PARAM),
    DEFINE_UINT_PARAM(tD_D,DEV_PARAM),
    DEFINE_UINT_PARAM(tRFCpb,DEV_PARAM),
    DEFINE_UINT_PARAM(tPBR2PBR,DEV_PARAM),
    DEFINE_UINT_PARAM(tPBR2PBR_L,DEV_PARAM),
    DEFINE_UINT_PARAM(tPBR2ACT,DEV_PARAM),
    DEFINE_UINT_PARAM(NUM_CHANS,SYS_PARAM),
    DEFINE_BOOL_PARAM(MPAM_MAPPING_TIMEOUT,SYS_PARAM) ,
    DEFINE_UINTARRAY_PARAM(MPAM_TIMEOUT_RD,SYS_PARAM) ,
    DEFINE_UINTARRAY_PARAM(MPAM_TIMEOUT_WR,SYS_PARAM) ,
    DEFINE_UINTARRAY_PARAM(MPAM_ADAPT_RD,SYS_PARAM) ,
    DEFINE_UINTARRAY_PARAM(MPAM_ADAPT_WR,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRIORITY_PASS_ENABLE,SYS_PARAM) ,
    DEFINE_STRING_PARAM(DDR_TYPE,SYS_PARAM),
    DEFINE_STRING_PARAM(DDR_MODE,SYS_PARAM),
    DEFINE_STRING_PARAM(DRAM_VENDOR,SYS_PARAM),
    DEFINE_STRING_PARAM(DRAM_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(DMC_RATE,SYS_PARAM),
    DEFINE_UINT_PARAM(ABR_PSTPND_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(PBR_PSTPND_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(PRE_NUM_SEND_PBR,DEV_PARAM),
    DEFINE_BOOL_PARAM(FASTWAKEUP_EN,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PREDICT_FASTWAKEUP,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(QOS_INV,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(GREEN_PATH_DIS,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(LQOS_BP_EN,SYS_PARAM) ,
    DEFINE_UINT_PARAM(LQOS_BP_LEVEL,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(TIMEOUT_ENABLE,SYS_PARAM) ,
    DEFINE_UINT_PARAM(QOS_POLICY,SYS_PARAM) ,
    DEFINE_UINT_PARAM(TIMEOUT_MODE,SYS_PARAM) ,
    DEFINE_UINT_PARAM(RDATA_TYPE,DEV_PARAM),
    DEFINE_BOOL_PARAM(PAGE_ADAPT_EN,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PAGE_TIMEOUT_EN,SYS_PARAM) ,
    DEFINE_UINT_PARAM(OPENPAGE_TIME_RD,SYS_PARAM) ,
    DEFINE_UINT_PARAM(OPENPAGE_TIME_WR,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(ENH_PAGE_ADPT_EN,SYS_PARAM) ,
    DEFINE_UINT_PARAM(ENH_PAGE_ADPT_WIN,SYS_PARAM) ,
    DEFINE_UINTARRAY_PARAM(ENH_PAGE_ADPT_LVL,DEV_PARAM),
    DEFINE_UINTARRAY_PARAM(ENH_PAGE_ADPT_TIME,DEV_PARAM),
    DEFINE_UINT_PARAM(DMC_BW_WIN,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(DMC_BW_LEVEL,DEV_PARAM),
    DEFINE_BOOL_PARAM(PAGE_ADPT_EN,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PAGE_WIN_MODE,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PAGE_WIN_SIZE,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PAGE_OPC_TH,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PAGE_PPC_TH,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PAGE_ADPT_STEP,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PAGE_TIME_MAX,SYS_PARAM) ,
    DEFINE_UINT_PARAM(DRESP_BP_TH,SYS_PARAM) ,
    DEFINE_STRING_PARAM(SYSTEM_CONFIG,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(STATE_LOG,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_TRACE,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_READ,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_RDATA,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_SCH,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_EXEC,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_IDLE_LAT,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_LATENCY,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_DRAM_TRACE,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_UT_TRACE,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PRINT_CMD_NUM,SYS_PARAM) ,
    DEFINE_UINT64HEX_PARAM(PRINT_CH_OHOT,SYS_PARAM),
    DEFINE_BOOL_PARAM(PRINT_BW,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PRINT_BW_WIN,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PERFECT_DMC_EN,SYS_PARAM) ,
    DEFINE_UINT_PARAM(PERFECT_DMC_DELAY,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(DROP_WRITE_CMD,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(LAT_INC_BP,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(FORCE_BAINTLV_EN,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(POWER_EN,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(BA_SHIFT_DIR,SYS_PARAM) ,
    DEFINE_UINT_PARAM(BA_SHIFT_BIT,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(SLOT_FIFO,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(TIME_ASSERT_EN,SYS_PARAM) ,
    DEFINE_UINT_PARAM(EXEC_NUMBER,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PBR_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(ENH_PBR_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(ENH_PBR_CEIL_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(DERATING_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(DERATING_RATIO,SYS_PARAM) ,
    DEFINE_BOOL_PARAM(PBR_PARA_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(AREF_OFFSET_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(SBR_IDLE_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_REQ_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_FRCST_NUM,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_WEIGHT_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_WEIGHT_ENH_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_GAP_CNT,SYS_PARAM),
    DEFINE_BOOL_PARAM(SBR_IDLE_ADAPT_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_IDLE_ADAPT_WIN,SYS_PARAM),
    DEFINE_UINT_PARAM(SBR_IDLE_ADAPT_LEVEL,SYS_PARAM),
    DEFINE_BOOL_PARAM(SEND_DSTREF_SERIAL,SYS_PARAM),
    DEFINE_BOOL_PARAM(PD_PBR_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(FG_REFRESH_TH,SYS_PARAM),

    DEFINE_FLOAT_PARAM(POWER_RDINC_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_RDWRAP_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_WRINC_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_WRWRAP_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_RDATA_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_WDATA_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_ACT_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PREP_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PRES_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PREA_K,DEV_PARAM),
    DEFINE_FLOATARRAY_PARAM(POWER_RD_K,DEV_PARAM),
    DEFINE_FLOATARRAY_PARAM(POWER_QUEUE_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PBR_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_ABR_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_R2W_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_W2R_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_RNKSW_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PDE_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_ASREFE_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_SRPDE_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PDX_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_ASREFX_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_SRPDX_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_IDLE_K,DEV_PARAM),
    DEFINE_FLOAT_PARAM(POWER_PDCC_K,DEV_PARAM),
    DEFINE_FLOATARRAY_PARAM(POWER_WR_K,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW23,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW22,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW21,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW20,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW19,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW18,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW17,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW16,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW15,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW14,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW13,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW12,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW11,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW10,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW9,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW8,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW7,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW6,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW5,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW4,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW3,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW2,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW1,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_ROW0,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_CH,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_RA2,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_RA1,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_RA0,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA6,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA5,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA4,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA3,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA2,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA1,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BA0,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BG4,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BG3,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BG2,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BG1,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_BG0,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_SID2,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_SID1,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_SID0,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL10,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL9,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL8,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL7,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL6,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL5,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL4,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL3,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL2,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL1,DEV_PARAM),
    DEFINE_UINT64HEX_PARAM(MATRIX_COL0,DEV_PARAM),

    //Memory Controller related parameters
    DEFINE_UINT_PARAM(TRANS_QUEUE_DEPTH,SYS_PARAM),
    DEFINE_UINT_PARAM(TABLE_DEPTH,SYS_PARAM),
    //Power
    DEFINE_UINTARRAY_PARAM(TIMEOUT_PRI_RD,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(TIMEOUT_PRI_WR,SYS_PARAM),
    DEFINE_BOOL_PARAM(PRI_ADPT_ENABLE,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(ADAPT_PRI_RD,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(ADAPT_PRI_WR,SYS_PARAM),
    DEFINE_UINT_PARAM(STATE_TIME,SYS_PARAM),
    // debug flags
    DEFINE_BOOL_PARAM(DEBUG_BUS,SYS_PARAM),
    DEFINE_BOOL_PARAM(RD_APRE_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(WR_APRE_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(ENHAN_RD_AP_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(ENHAN_WR_AP_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(AREF_EN,SYS_PARAM),

    DEFINE_BOOL_PARAM(GRP_RW_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(BG_ROTATE_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(RCMD_BANK_ARB_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(WCMD_BANK_ARB_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(RCMD_BANK_ARB_PRI,SYS_PARAM),
    DEFINE_UINT_PARAM(WCMD_BANK_ARB_PRI,SYS_PARAM),
    DEFINE_BOOL_PARAM(WCK_ALWAYS_ON,SYS_PARAM),
    DEFINE_BOOL_PARAM(CAS_FS_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(CAS_FS_TH,SYS_PARAM),
    DEFINE_UINT_PARAM(CORE_CONCURR,SYS_PARAM),
    DEFINE_UINT_PARAM(CORE_CONCURR_PRD,SYS_PARAM),
    DEFINE_UINT_PARAM(ENGRP_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(EXGRP_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(CMD_WLEVELL,SYS_PARAM),
    DEFINE_UINT_PARAM(CMD_WLEVELH,SYS_PARAM),
    DEFINE_UINT_PARAM(SERIAL_RLEVELL,SYS_PARAM),
    DEFINE_UINT_PARAM(SERIAL_RLEVELH,SYS_PARAM),
    DEFINE_UINT_PARAM(SERIAL_WLEVELL,SYS_PARAM),
    DEFINE_UINT_PARAM(SERIAL_WLEVELH,SYS_PARAM),
    DEFINE_UINT_PARAM(RLEVEL_R2W,SYS_PARAM),
    DEFINE_UINT_PARAM(ALEVEL_W2R,SYS_PARAM),
    DEFINE_BOOL_PARAM(HARDWARE_RHIT_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(CMD_RLEVELL,SYS_PARAM),
    DEFINE_UINT_PARAM(CMD_RLEVELH,SYS_PARAM),
    DEFINE_UINT_PARAM(RHIT_RW_CMD_NUM,SYS_PARAM),
    DEFINE_UINT_PARAM(RHIT_ACT_CMD_NUM,SYS_PARAM),
    DEFINE_BOOL_PARAM(RWGRP_TRANS_BY_TOUT,SYS_PARAM),
    DEFINE_UINT_PARAM(RWGRP_AUTO_BW,SYS_PARAM),
    DEFINE_BOOL_PARAM(GRP_RANK_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(GRP_RANK_MODE,SYS_PARAM),
    DEFINE_BOOL_PARAM(GRP_RANK_PREPB,SYS_PARAM),
    DEFINE_BOOL_PARAM(GRP_RANK_PREAB,SYS_PARAM),
    DEFINE_UINT_PARAM(GRP_RANK_LEVEL,SYS_PARAM),
    DEFINE_BOOL_PARAM(SIMPLE_GRP_RANK_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(READ_RANK_GRP_LEVEL0_H,SYS_PARAM),
    DEFINE_UINT_PARAM(READ_RANK_GRP_LEVEL0_L,SYS_PARAM),
    DEFINE_UINT_PARAM(READ_RANK_GRP_LEVEL1_H,SYS_PARAM),
    DEFINE_UINT_PARAM(READ_RANK_GRP_LEVEL1_L,SYS_PARAM),
    DEFINE_BOOL_PARAM(SIMPLE_GRP_SID_EN,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(GRP_SID_LEVEL,SYS_PARAM),
    DEFINE_BOOL_PARAM(RCMD_HQOS_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(RCMD_HQOS_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(SWITCH_HQOS_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(CPU_MID_START,SYS_PARAM),
    DEFINE_UINT_PARAM(CPU_MID_END,SYS_PARAM),
    DEFINE_BOOL_PARAM(RCMD_HQOS_W2R_SWITCH_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(RCMD_HQOS_W2R_RLEVELH,SYS_PARAM),
    DEFINE_UINT_PARAM(RCMD_HQOS_RANK_SWITCH_LEVELH,SYS_PARAM),
    DEFINE_UINT_PARAM(RCMD_HQOS_RANK_SWITCH_LEVELL,SYS_PARAM),
    DEFINE_UINT_PARAM(RCMD_HQOS_RANK_SWITCH_ROWHIT_LEVEL,SYS_PARAM),
    DEFINE_BOOL_PARAM(RCMD_HQOS_RANK_SWITCH_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(RHIT_HQOS_BREAK_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(RHIT_HQOS_BREAK_OTH_RCMD_LEVEL,SYS_PARAM),
    DEFINE_BOOL_PARAM(BYP_ACT_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(RHIT_BREAK_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(RHIT_BREAK_LEVEL,SYS_PARAM),
    DEFINE_UINT_PARAM(RW_GRPCHG_W2R_TH,SYS_PARAM),
    DEFINE_UINT_PARAM(RW_GRPCHG_R2W_TH,SYS_PARAM),
    DEFINE_BOOL_PARAM(DMC_V580,SYS_PARAM),
    DEFINE_BOOL_PARAM(DMC_V590,SYS_PARAM),
    DEFINE_BOOL_PARAM(DMC_V596,SYS_PARAM),
    DEFINE_BOOL_PARAM(EARLY_TCCDL_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(TRFC_CC_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(WB_WDEPTH,SYS_PARAM),
    DEFINE_UINT_PARAM(WB_RDEPTH,SYS_PARAM),
    DEFINE_BOOL_PARAM(MERGE_ENABLE,SYS_PARAM),
    DEFINE_BOOL_PARAM(FORWARD_ENABLE,SYS_PARAM),
    DEFINE_BOOL_PARAM(DYN_BYP_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(GBUF_RCMD_BLOCK_PBR,SYS_PARAM),
    DEFINE_BOOL_PARAM(GBUF_RD_BRK_WFLUSH_CMD,SYS_PARAM),
    DEFINE_UINT_PARAM(GBUF_RCMD_TIMEOUT,SYS_PARAM),
    DEFINE_UINT_PARAM(GBUF_WCMD_PRIADAPT,SYS_PARAM),
    DEFINE_BOOL_PARAM(RQ_RNKCONF_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(RQ_ADCONF_PUSH_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(CMD_ROW_ORDER,SYS_PARAM),
    DEFINE_UINT_PARAM(TOTAL_RCMD_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(RQ_BACONF_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(WQ_BACONF_MODE,SYS_PARAM),
    DEFINE_BOOL_PARAM(RO_HIT_EN,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(GRP_MODE_LEVEL0,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(GRP_MODE_LEVEL1,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(GRP_MODE_LEVEL2,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(GRP_MODE_LEVEL3,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(BANK_CMD_TH,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(NO_CMD_SCH_TH,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WGRP_RANK_MODE,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_LEVEL0,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_LEVEL1,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_LEVEL2,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_LEVEL3,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_MOST_LEVEL0,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_MOST_LEVEL1,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_MOST_LEVEL2,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(WR_MOST_LEVEL3,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(RD_LEVEL0,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(RD_LEVEL1,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(RD_LEVEL2,SYS_PARAM),
    DEFINE_UINTARRAY_PARAM(RD_LEVEL3,SYS_PARAM),
    DEFINE_FLOAT_PARAM(IDD01,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD02H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD02L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD0Q,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2P1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2P2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2P2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2PQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2PS1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2PS2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2PS2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2PSQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2N1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2N2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2N2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2NQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2NS1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2NS2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2NS2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD2NSQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3P1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3P2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3P2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3PQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3PS1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3PS2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3PS2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3PSQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3N1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3N2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3N2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3NQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3NS1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3NS2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3NS2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD3NSQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4R1_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4R2H_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4R2L_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4RQ_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4R1_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4R2H_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4R2L_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4RQ_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4W1_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4W2H_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4W2L_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4WQ_BG,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4W1_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4W2H_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4W2L_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD4WQ_BK,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD51,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD52H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD52L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5Q,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5AB1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5AB2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5AB2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5ABQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5PB1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5PB2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5PB2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD5PBQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD61,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD62H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD62L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD6Q,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD6DS1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD6DS2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD6DS2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(IDD6DSQ,DEV_PARAM),
    DEFINE_FLOAT_PARAM(VDD1,DEV_PARAM),
    DEFINE_FLOAT_PARAM(VDD2H,DEV_PARAM),
    DEFINE_FLOAT_PARAM(VDD2L,DEV_PARAM),
    DEFINE_FLOAT_PARAM(VDDQH,DEV_PARAM),
    DEFINE_FLOAT_PARAM(VDDQL,DEV_PARAM),
    DEFINE_BOOL_PARAM(EM_ENABLE,SYS_PARAM),
    DEFINE_UINT_PARAM(EM_MODE,SYS_PARAM),
    DEFINE_BOOL_PARAM(RMW_ENABLE,SYS_PARAM),
    DEFINE_UINT_PARAM(RMW_CMD_MODE,SYS_PARAM),
    DEFINE_UINT_PARAM(RMW_QUE_DEPTH,SYS_PARAM),
    DEFINE_UINT_PARAM(RMW_CONF_SIZE,SYS_PARAM),
    DEFINE_UINT_PARAM(GRT_FIFO_DEPTH,SYS_PARAM),
    DEFINE_UINT_PARAM(TRANS_FIFO_DEPTH,SYS_PARAM),
    DEFINE_UINT_PARAM(ROW_SEL,SYS_PARAM),
    DEFINE_BOOL_PARAM(WCMD_MERGE_EN,SYS_PARAM),
    DEFINE_UINT_PARAM(WRITE_MERGE_BUFFER_DEPTH,SYS_PARAM),
    DEFINE_BOOL_PARAM(UNPAIRED_TO_RMW_EN,SYS_PARAM),
    DEFINE_BOOL_PARAM(WRITE_BUFFER_ENABLE,SYS_PARAM), {"", NULL, UINT, SYS_PARAM, false}
    // tracer value to signify end of list; if you delete it, epic fail will result
};

void IniReader::WriteParams(std::ofstream &visDataOut, paramType type) {
    for (size_t i=0; configMap[i].variablePtr != NULL; i++) {
        if (configMap[i].parameterType == type) {
            visDataOut<<configMap[i].iniKey<<"=";
            switch (configMap[i].variableType) {
                //parse and set each type of variable
                case UINT:
                    visDataOut << *((unsigned *)configMap[i].variablePtr);
                    break;
                case UINT64:
                case UINT64HEX:
                    visDataOut << *((uint64_t *)configMap[i].variablePtr);
                    break;
                case FLOAT:
                    visDataOut << *((float *)configMap[i].variablePtr);
                    break;
                case STRING:
                    visDataOut << *((string *)configMap[i].variablePtr);
                    break;
                case BOOL:
                    if (*((bool *)configMap[i].variablePtr)) {
                        visDataOut <<"true";
                    } else {
                        visDataOut <<"false";
                    }
                    break;
                case UINTARRAY:
                case FLOATARRAY:
                    break; //TBD
            }
            visDataOut << endl;
        }
    }
    if (type == SYS_PARAM) {
        visDataOut<<"NUM_RANKS="<<NUM_RANKS <<"\n";
    }
}
void IniReader::WriteValuesOut(std::ofstream &visDataOut) {
    visDataOut<<"!!SYSTEM_INI"<<endl;

    WriteParams(visDataOut, SYS_PARAM);
    visDataOut<<"!!DEVICE_INI"<<endl;

    WriteParams(visDataOut, DEV_PARAM);
    visDataOut<<"!!EPOCH_DATA"<<endl;
}

void IniReader::SetKey(string key, string valueString, bool isSystemParam, size_t lineNumber) {
    size_t i;
    unsigned intValue;
    uint64_t int64Value;
    uint64_t int64ValueHex;
    float floatValue;
    unsigned start = 1;
    unsigned end = 0;

    for (i=0; configMap[i].variablePtr != NULL; i++) {
        istringstream iss(valueString);
        // match up the string in the config map with the key we parsed
        if (key.compare(configMap[i].iniKey) == 0) {
            switch (configMap[i].variableType) {
                //parse and set each type of variable
                case UINT: {
                    if ((iss >> dec >> intValue).fail()) {
                        ERROR("could not parse line "<<lineNumber<<" (non-numeric value '"<<valueString<<"')?");
                    }
                    *((unsigned *)configMap[i].variablePtr) = intValue;
                    if (DEBUG_INI_READER) {
                        DEBUG("\t - SETTING "<<configMap[i].iniKey<<"="<<intValue);
                    }
                    break;
                }
                case UINT64: {
                    if ((iss >> dec >> int64Value).fail()) {
                        ERROR("could not parse line "<<lineNumber<<" (non-numeric value '"<<valueString<<"')?");
                    }
                    *((uint64_t *)configMap[i].variablePtr) = int64Value;
                    if (DEBUG_INI_READER) {
                        DEBUG("\t - SETTING "<<configMap[i].iniKey<<"="<<int64Value);
                    }
                    break;
                }
                case UINT64HEX: {
                    if ((iss >> hex >> int64ValueHex).fail()) {
                        ERROR("could not parse line "<<lineNumber<<" (non-numeric value '"<<valueString<<"')?");
                    }
                    *((uint64_t *)configMap[i].variablePtr) = int64ValueHex;
                    if (DEBUG_INI_READER) {
                        DEBUG("\t - SETTING "<<configMap[i].iniKey<<"="<<int64ValueHex);
                    }
                    break;
                }
                case FLOAT: {
                    if ((iss >> dec >> floatValue).fail()) {
                        ERROR("could not parse line "<<lineNumber<<" (non-numeric value '"<<valueString<<"')?");
                    }
                    *((float *)configMap[i].variablePtr) = floatValue;
                    if (DEBUG_INI_READER) {
                        DEBUG("\t - SETTING "<<configMap[i].iniKey<<"="<<floatValue);
                    }
                    break;
                }
                case STRING: {
                    valueString.erase(valueString.begin());
                    valueString.erase(valueString.end() - 1);
                    *((string *)configMap[i].variablePtr) = string(valueString);
                    if (DEBUG_INI_READER) {
                        DEBUG("\t - SETTING "<<configMap[i].iniKey<<"="<<valueString);
                    }
                    break;
                }
                case BOOL: {
                    if (valueString == "true" || valueString == "1") {
                        *((bool *)configMap[i].variablePtr) = true;
                    } else {
                        *((bool *)configMap[i].variablePtr) = false;
                    }
                    break;
                }
                case UINTARRAY: {
                    unsigned value_uint = 0;
                    start = 1;
                    end = 0;
                    if (MAP_CONFIG[key].size() == 0) {
                        while (end < valueString.size()) {
                            end = valueString.find(",", start + 1);
                            istringstream iss_array(valueString.substr(start, end));
                            iss_array >> dec >> value_uint;
                            MAP_CONFIG[key].push_back(value_uint);
                            start = end + 1;
                        }
                    }
                    break;
                }
                case FLOATARRAY: {
                    float value_float = 0;
                    start = 1;
                    end = 0;
                    if (MAP_CONFIG[key].size() == 0) {
                        while (end < valueString.size()) {
                            end = valueString.find(",", start + 1);
                            istringstream iss_array(valueString.substr(start, end));
                            iss_array >> dec >> value_float;
                            MAP_CONFIG[key].push_back(value_float);
                            start = end + 1;
                        }
                    }
                    break;
                }
            }
            // lineNumber == 0 implies that this is an override parameter
            // from the command line, so don't bother doing these checks
            // use the pointer stored in the config map to set the value of the variable
            // to make sure all parameters are in the ini file
            configMap[i].wasSet = true;
            break;
        }
    }

    if (configMap[i].variablePtr == NULL) {
        DEBUG("WARNING: UNKNOWN KEY '"<<key<<"' IN INI FILE");
    }
}

void IniReader::ReadIniFile(istream &iniFile, bool isSystemFile)
{
    string line;
    string key,valueString;

    size_t commentIndex, equalsIndex;
    size_t lineNumber=0;

    while (!iniFile.eof()) {
        lineNumber++;
        getline(iniFile, line);
        //this can happen if the filename is actually a directory
        if (iniFile.bad()) {
            ERROR("Cannot read ini file");
            assert(0);
        }
        // skip zero-length lines
        if (line.size() == 0) {
            continue;
        }
        while (1) {
            size_t pos = line.find(" ");
            if (pos == string::npos) break;
            line.erase(pos, 1);
        }
        //search for a comment char
        if ((commentIndex = line.find_first_of("#")) != string::npos) {
            //if the comment char is the first char, ignore the whole line
            if (commentIndex == 0) {
                continue;
            }
            //truncate the line at first comment before going on
            line = line.substr(0,commentIndex);
        }
        // trim off the end spaces that might have been between the value and comment char
        size_t whiteSpaceEndIndex = line.find_last_not_of(" \t");
        if (whiteSpaceEndIndex != string::npos) {
            line = line.substr(0,whiteSpaceEndIndex+1);
        }

        // at this point line should be a valid, commentless string

        // a line has to have an equals sign
        if ((equalsIndex = line.find_first_of("=")) == string::npos) {
            ERROR(" Malformed Line "<<lineNumber<<" (missing equals)");
            assert(0);
        }
        size_t strlen = line.size();
        // all characters before the equals are the key
        key = line.substr(0, equalsIndex);
        // all characters after the equals are the value
        valueString = line.substr(equalsIndex+1,strlen-equalsIndex);

        IniReader::SetKey(key, valueString, isSystemFile, lineNumber);
        // got to the end of the config map without finding the key
    }
}

#ifdef SYSARCH_PLATFORM
void IniReader::ModifyParameter(HALib::Configurable* cfg) {
#else
void IniReader::ModifyParameter(Configurable cfg) {
#endif
    if (WRITE_BUFFER_ENABLE) {
        if (IS_DDR5 && IS_DDR4) {
            ENGRP_LEVEL = 4;
            EXGRP_LEVEL = 2;
            //CMD_WLEVELL = 4;
            //CMD_WLEVELH = 7;
            CMD_WLEVELL = 14; // better level
            CMD_WLEVELH = 16; // better level
            SERIAL_RLEVELL = 0;
            SERIAL_RLEVELH = 1024;
            SERIAL_WLEVELL = 0;
            SERIAL_WLEVELH = 1024;
            RLEVEL_R2W = 8;
        }
    }

    if (PRINT_IDLE_LAT) {
        AREF_EN = false;
        PBR_EN = false;
        PD_ENABLE = false;
        ASREF_ENABLE = false;
        ASREF_ADAPT_EN = false;
    }

    if (!AREF_EN) PBR_EN = false;
    if (!PBR_EN) ENH_PBR_EN = false;
    if (DMC_V590 || DMC_V596) tXP = tXP_V590;
    else if (DMC_V580) tXP = tXP_V580;
    else tXP = tXP_V570;

    if (DMC_V596) {
        ABR_PSTPND_LEVEL = 6;
        PBR_PSTPND_LEVEL = 5;
    }

    if (!DMC_V590 && !DMC_V596) PD_PBR_EN = false;

    if (IS_GD1) {
        PD_ENABLE = false;
        ASREF_ENABLE = false;
        ASREF_ADAPT_EN = false;
        if (IS_GD1 && DMC_RATE == 2133) {
            RD_APRE_EN = true;
            WR_APRE_EN = true;
        }
    } else if (IS_GD2) {
        SBR_REQ_MODE = 1;
    } else if (IS_G3D) {
        PD_ENABLE = false;
        ASREF_ENABLE = false;
        RD_APRE_EN = true;
        WR_APRE_EN = true;
        GRP_RW_EN = false;
    } else if (IS_DDR4) {
        PD_ENABLE = false;
        ASREF_ENABLE = false;
        ASREF_ADAPT_EN = false;
        PBR_EN = false;
        ENGRP_LEVEL = 4;
        EXGRP_LEVEL = 2;
        CMD_RLEVELL = 2;
        CMD_RLEVELH = 4;
        CMD_WLEVELL = 21;
        CMD_WLEVELH = 59;
        SERIAL_RLEVELL = 16;
        SERIAL_RLEVELH = 64;
        SERIAL_WLEVELL = 25;
        SERIAL_WLEVELH = 111;
        RLEVEL_R2W = 24;
        RHIT_RW_CMD_NUM = 200;
        RHIT_ACT_CMD_NUM = 76;
    }

    if ((DMC_V590 || DMC_V596) && ASREF_ADAPT_EN) ASREF_PRD = MAP_CONFIG["ASREF_ADAPT_PRD"][3];

    if (!PBR_EN) SBR_IDLE_EN = false;

    if (GRP_RANK_EN) GRP_RW_EN = false;

    MATRIX_BA6 = !BA_SHIFT_DIR ? (MATRIX_BA6 << BA_SHIFT_BIT) : (MATRIX_BA6 >> BA_SHIFT_BIT);
    MATRIX_BA5 = !BA_SHIFT_DIR ? (MATRIX_BA5 << BA_SHIFT_BIT) : (MATRIX_BA5 >> BA_SHIFT_BIT);
    MATRIX_BA4 = !BA_SHIFT_DIR ? (MATRIX_BA4 << BA_SHIFT_BIT) : (MATRIX_BA4 >> BA_SHIFT_BIT);
    MATRIX_BA3 = !BA_SHIFT_DIR ? (MATRIX_BA3 << BA_SHIFT_BIT) : (MATRIX_BA3 >> BA_SHIFT_BIT);
    MATRIX_BA2 = !BA_SHIFT_DIR ? (MATRIX_BA2 << BA_SHIFT_BIT) : (MATRIX_BA2 >> BA_SHIFT_BIT);
    MATRIX_BA1 = !BA_SHIFT_DIR ? (MATRIX_BA1 << BA_SHIFT_BIT) : (MATRIX_BA1 >> BA_SHIFT_BIT);
    MATRIX_BA0 = !BA_SHIFT_DIR ? (MATRIX_BA0 << BA_SHIFT_BIT) : (MATRIX_BA0 >> BA_SHIFT_BIT);
    MATRIX_BG4 = !BA_SHIFT_DIR ? (MATRIX_BG4 << BA_SHIFT_BIT) : (MATRIX_BG4 >> BA_SHIFT_BIT);
    MATRIX_BG3 = !BA_SHIFT_DIR ? (MATRIX_BG3 << BA_SHIFT_BIT) : (MATRIX_BG3 >> BA_SHIFT_BIT);
    MATRIX_BG2 = !BA_SHIFT_DIR ? (MATRIX_BG2 << BA_SHIFT_BIT) : (MATRIX_BG2 >> BA_SHIFT_BIT);
    MATRIX_BG1 = !BA_SHIFT_DIR ? (MATRIX_BG1 << BA_SHIFT_BIT) : (MATRIX_BG1 >> BA_SHIFT_BIT);
    MATRIX_BG0 = !BA_SHIFT_DIR ? (MATRIX_BG0 << BA_SHIFT_BIT) : (MATRIX_BG0 >> BA_SHIFT_BIT);

    IS_LP4 = DDR_TYPE == LPDDR4;
    IS_LP5 = DDR_TYPE == LPDDR5;
    IS_LP6 = DDR_TYPE == LPDDR6;
    IS_GD1 = DDR_TYPE == GUARDIANS_D1;
    IS_GD2 = DDR_TYPE == GUARDIANS_D2;
    IS_G3D = DDR_TYPE == GUARDIANS_3D;
    IS_DDR4 = DDR_TYPE == DDR4;
    IS_DDR5 = DDR_TYPE == DDR5;
    IS_HBM2E = DDR_TYPE == HBM2E;
    IS_HBM3 = DDR_TYPE == HBM3;

#ifdef SYSARCH_PLATFORM
    FASTWAKEUP_EN = cfg->getBool("fast_wakeup_en");

    // Avoid multi core address range
    uint64_t matrix_max = 0x0;
    unsigned zero_cnt = 0;
    if (MATRIX_RA2 > matrix_max) matrix_max = MATRIX_RA2;
    if (MATRIX_RA1 > matrix_max) matrix_max = MATRIX_RA1;
    if (MATRIX_RA0 > matrix_max) matrix_max = MATRIX_RA0;
    if (MATRIX_ROW0 > matrix_max) matrix_max = MATRIX_ROW0;
    if (MATRIX_ROW1 > matrix_max) matrix_max = MATRIX_ROW1;
    if (MATRIX_ROW2 > matrix_max) matrix_max = MATRIX_ROW2;
    if (MATRIX_ROW3 > matrix_max) matrix_max = MATRIX_ROW3;
    if (MATRIX_ROW4 > matrix_max) matrix_max = MATRIX_ROW4;
    if (MATRIX_ROW5 > matrix_max) matrix_max = MATRIX_ROW5;
    if (MATRIX_ROW6 > matrix_max) matrix_max = MATRIX_ROW6;
    if (MATRIX_ROW7 > matrix_max) matrix_max = MATRIX_ROW7;
    if (MATRIX_ROW8 > matrix_max) matrix_max = MATRIX_ROW8;
    if (MATRIX_ROW9 > matrix_max) matrix_max = MATRIX_ROW9;
    if (MATRIX_ROW10 > matrix_max) matrix_max = MATRIX_ROW10;
    if (MATRIX_ROW11 > matrix_max) matrix_max = MATRIX_ROW11;
    if (MATRIX_ROW12 > matrix_max) matrix_max = MATRIX_ROW12;
    if (MATRIX_ROW13 > matrix_max) matrix_max = MATRIX_ROW13;
    if (MATRIX_ROW14 > matrix_max) matrix_max = MATRIX_ROW14;
    if (MATRIX_ROW15 > matrix_max) matrix_max = MATRIX_ROW15;
    if (MATRIX_ROW16 > matrix_max) matrix_max = MATRIX_ROW16;
    if (MATRIX_ROW17 > matrix_max) matrix_max = MATRIX_ROW17;
    if (MATRIX_ROW18 > matrix_max) matrix_max = MATRIX_ROW18;
    if (MATRIX_ROW19 > matrix_max) matrix_max = MATRIX_ROW19;
    if (MATRIX_ROW20 > matrix_max) matrix_max = MATRIX_ROW20;
    if (MATRIX_ROW21 > matrix_max) matrix_max = MATRIX_ROW21;
    if (MATRIX_ROW22 > matrix_max) matrix_max = MATRIX_ROW22;
    if (MATRIX_ROW23 > matrix_max) matrix_max = MATRIX_ROW23;

    if (MATRIX_ROW0 == 0) {MATRIX_ROW0 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW1 == 0) {MATRIX_ROW1 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW2 == 0) {MATRIX_ROW2 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW3 == 0) {MATRIX_ROW3 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW4 == 0) {MATRIX_ROW4 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW5 == 0) {MATRIX_ROW5 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW6 == 0) {MATRIX_ROW6 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW7 == 0) {MATRIX_ROW7 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW8 == 0) {MATRIX_ROW8 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW9 == 0) {MATRIX_ROW9 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW10 == 0) {MATRIX_ROW10 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW11 == 0) {MATRIX_ROW11 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW12 == 0) {MATRIX_ROW12 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW13 == 0) {MATRIX_ROW13 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW14 == 0) {MATRIX_ROW14 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW15 == 0) {MATRIX_ROW15 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW16 == 0) {MATRIX_ROW16 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW17 == 0) {MATRIX_ROW17 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW18 == 0) {MATRIX_ROW18 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW19 == 0) {MATRIX_ROW19 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW20 == 0) {MATRIX_ROW20 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW21 == 0) {MATRIX_ROW21 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW22 == 0) {MATRIX_ROW22 = matrix_max << zero_cnt; zero_cnt ++;}
    if (MATRIX_ROW23 == 0) {MATRIX_ROW23 = matrix_max << zero_cnt; zero_cnt ++;}
#endif
}

void IniReader::CheckParameter() {
    if (NUM_CHANS == 0) {
        ERROR("Zero channels");
        assert(0);
    }

    if (RDATA_TYPE >= 2) {
        ERROR("RDATA_TYPE error! Currner is "<<RDATA_TYPE<<".");
        assert(0);
    }

    if (GRP_RANK_MODE >= 2) {
        ERROR("GRP_RANK_MODE error! Currner is "<<GRP_RANK_MODE<<".");
        assert(0);
    }

    if (GRP_RANK_PREPB && GRP_RANK_PREAB) {
        ERROR("Set both GRP_RANK_PREPB and GRP_RANK_PREAB true is error.");
        assert(0);
    }

    if (CORE_CONCURR == 0) {
        ERROR("CORE_CONCURR error! Currner is "<<CORE_CONCURR<<".");
        assert(0);
    }

    for (auto map_cfg : MAP_CONFIG) {
        auto first = map_cfg.first;
        auto second = map_cfg.second;
        if (first == "TIMEOUT_PRI_RD" || first == "TIMEOUT_PRI_WR" ||
                first == "ADAPT_PRI_RD" || first == "ADAPT_PRI_WR") {
            if (second.size() != 7) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 7.");
                assert(0);
            }
        }
        if (first == "MPAM_TIMEOUT_RD" || first == "MPAM_TIMEOUT_WR" ||
                first == "MPAM_ADAPT_RD" || first == "MPAM_ADAPT_WR") {
            if (second.size() != 16) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 16.");
                assert(0);
            }
        }
        if (first == "BANK_CMD_TH" || first == "WR_LEVEL0" || first == "WR_LEVEL1" || first == "WR_LEVEL2" ||
                first == "WR_LEVEL3" || first == "WR_MOST_LEVEL0" || first == "WR_MOST_LEVEL1" ||
                first == "WR_MOST_LEVEL2" || first == "WR_MOST_LEVEL3" || first == "RD_LEVEL0" ||
                first == "RD_LEVEL1" || first == "RD_LEVEL2" || first == "RD_LEVEL3" || first == "NO_CMD_SCH_TH" ||
                first == "GRP_MODE_LEVEL0" || first == "GRP_MODE_LEVEL1" || first == "GRP_MODE_LEVEL2" ||
                first == "GRP_MODE_LEVEL3" || first == "WGRP_RANK_MODE") {
            if (second.size() != 5) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 5.");
                assert(0);
            }
        }
        if (first == "ASREF_ADAPT_LEVEL") {
            if (second.size() != 3) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 3.");
                assert(0);
            }
        }
        if (first == "ASREF_ADAPT_PRD") {
            if (second.size() != 4) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 4.");
                assert(0);
            }
        }
        if (first == "ENH_PAGE_ADPT_LVL") {
            if (second.size() != 3) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 3.");
                assert(0);
            }
        }
        if (first == "ENH_PAGE_ADPT_TIME") {
            if (second.size() != 4) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 4.");
                assert(0);
            }
        }
        if (first == "DMC_BW_LEVEL") {
            if (second.size() != 3) {
                ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 3.");
                assert(0);
            }
        }
        if (POWER_EN) {
            if (first == "POWER_RD_K" || first == "POWER_WR_K") {
                if (second.size() != 6) {
                    ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be 6.");
                    assert(0);
                }
            }
            if (first == "POWER_QUEUE_K") {
                if (second.size() != TRANS_QUEUE_DEPTH) {
                    ERROR("Wrong "<<first<<" size: "<<second.size()<<", Must be "
                            <<TRANS_QUEUE_DEPTH<<".");
                    assert(0);
                }
            }
        }
    }

    unsigned dmc_bandwidth = DMC_RATE * DMC_DATA_BUS_BITS / WCK2DFI_RATIO / PAM_RATIO / 16;
    unsigned dram_bandwidth = DMC_RATE * JEDEC_DATA_BUS_BITS / 8;
    if (dmc_bandwidth < dram_bandwidth) {
        ERROR("DMC bandwidth not match DRAM! DMC is "<<dmc_bandwidth<<"MByte, DRAM is "
                <<dram_bandwidth<<"MByte.");
        assert(0);
    }

    if (SBR_WEIGHT_MODE >= 6) { // undefined mode
        ERROR("Unkown SBR_WEIGHT_MODE, mode is "<<SBR_WEIGHT_MODE);
        assert(0);
    }

    if (QOS_POLICY < 1 || QOS_POLICY > 2) { // undefined mode
        ERROR("Unkown QOS_POLICY, mode is "<<QOS_POLICY);
        assert(0);
    }

    if (EM_MODE >=3) { //undefined mode
        ERROR("Unkown EM_MODE, mode is "<<EM_MODE);
        assert(0);
    }
}

void IniReader::OverrideKeys(const OverrideMap *map) {
    if (!map) return;

    OverrideIterator it = map->begin();
    DEBUG("Key overrides from command line:");
    for (it=map->begin(); it != map->end(); it++) {
        string key = it->first;
        string value = it->second;
        DEBUG("\t'"<< key <<"'->'"<< value<< "'");
        IniReader::SetKey(key,value);
    }
}

bool IniReader::CheckIfAllSet() {
    // check to make sure all parameters that we exepected were set
    for (size_t i=0; configMap[i].variablePtr != NULL; i++) {
        if (!configMap[i].wasSet) {
            DEBUG("WARNING: KEY "<<configMap[i].iniKey<<" NOT FOUND IN INI FILE.");
            switch (configMap[i].variableType) {
                //the string and bool values can be defaulted, but generally
                //we need all the numeric values to be set to continue
                case UINT:
                case UINT64:
                case UINT64HEX:
                case FLOAT:
                    ERROR("Cannot continue without key '"<<configMap[i].iniKey<<"' set.");
                    return false;
                    break;
                case BOOL:
                    *((bool *)configMap[i].variablePtr) = false;
                    DEBUG("\tSetting Default: "<<configMap[i].iniKey<<"=false");
                    break;
                case STRING:
                    break;
                case UINTARRAY:
                case FLOATARRAY:
                    break; //TBD
            }
        }
    }
    return true;
}

/*
 * There is probably a way of doing this with templates, but since
 * we have the types defined as an enum, doing this with macros is trivial.
 *
 * Return value: 0 on success, -1 on error
 */
#define DEF_GETTER(_funcname, _type, _typename)                \
    int _funcname(const std::string& field, _type *val) {      \
        int i;                            \
        for (i=0; configMap[i].variablePtr != NULL; i++) {  \
            if (field.compare(configMap[i].iniKey))        \
                continue;                \
            if (configMap[i].variableType != _typename)    \
                return -1;                \
            *val = *(_type *)configMap[i].variablePtr;    \
            return 0;                    \
        }                            \
        return -1;                        \
    }

/* TODO: getter for strings is missing. Probably not that useful though */
DEF_GETTER(IniReader::getBool, bool, BOOL)
DEF_GETTER(IniReader::getUint, unsigned int, UINT)
DEF_GETTER(IniReader::getUint64, uint64_t, UINT64)
DEF_GETTER(IniReader::getUint64Hex, uint64_t, UINT64HEX)
DEF_GETTER(IniReader::getFloat, float, FLOAT)

void IniReader::InitEnumsFromStrings() {
}

getfile::getfile(string filename) {
    std::ifstream pfile;
    std::string line ,valueString;
    unsigned long key = 0;
    size_t commentIndex;
    pfile.open(filename.c_str());
    if (!pfile.is_open()) {
        return;
    }

    while (!pfile.eof()) {
        //getline(pfile,line)
        getline(pfile, line);
        line_message val;
        if (pfile.bad()) {
            std::cout << "cannot read drive file" << endl;
            return;
        }

        if (line.size() == 0) continue;
        if ((commentIndex = line.find_first_of(";")) != string::npos) {
            if (commentIndex == 0) continue;
            line = line.substr(0, commentIndex);
        }

        size_t whiteSpaceEndIndex = line.find_last_not_of(" \t");
        if (whiteSpaceEndIndex != string::npos) {
            line = line.substr(0, whiteSpaceEndIndex + 1);
        }
        size_t inindex;
        if ((inindex = line.find("INCR")) != string::npos) {
            val.issue = START;
            valueString = line.substr(inindex + 5, inindex + 8);
            key = strtoul(valueString.c_str(), NULL, 10);
        } else if ((inindex = line.find("Over")) != string::npos) {
            val.issue = END;
        } else if ((inindex = line.find("Data")) != string::npos) {
            val.issue = DAT;
            valueString = line.substr(inindex + 5, inindex + 8);
            key = strtoul(valueString.c_str(), NULL, 10);
        }

        size_t ns_index = line.find("ns");
        valueString = line.substr(1, ns_index - 1);
        if (val.issue == END) {
            val.task = strtoul(valueString.c_str(), NULL, 10);
        }

        size_t readindex;
        if ((readindex = line.find("Read")) != string::npos) {
            val.operation = "Read";
        } else if ((readindex = line.find("Write")) != string::npos) {
            val.operation = "Write";
        }

        size_t sizdindex;
        if ((sizdindex = line.find("len")) != string::npos) {
            valueString = line.substr(sizdindex + 5, 3);
            val.len = atoi(valueString.c_str());
        }
        size_t index0x;
        if ((index0x = line.find("0x")) != string::npos) {
            valueString = line.substr(index0x + 4,8);
            string line_l = line.substr(index0x,4);
            val.address_l = strtoul(valueString.c_str(),NULL,16);
            val.address_h = strtoul(line_l.c_str(),NULL,16);
        }

        if ((readindex = line.find("id")) != string::npos) {
            valueString = line.substr(readindex + 5, 4);
            val.id = strtoul(valueString.c_str(), NULL, 16);
        }

        if ((index0x = line.rfind("0x")) != string::npos) {
            valueString = line.substr(index0x , 10);
            if (val.issue == START || val.issue == DAT) {
                val.task = strtoul(valueString.c_str(), NULL, 16);
            } else {
                key = strtoul(valueString.c_str(), NULL, 16);
            }
        }

        if (START == val.issue) {
            if (start_valmap.find(key) != start_valmap.end()) {
                key = key + 1;
            }
            start_valmap[key] = val;
        } else if (END == val.issue) {
            if (end_valmap.find(key) != end_valmap.end()) {
                key = key + 1;
            }
            end_valmap[key] = val;
        } else if (DAT == val.issue) {
            if (data_valmap.find(key) != data_valmap.end()) {
                key = key + 1;
            }
            data_valmap[key] = val;
        }
    }
}

ostream &operator<<(ostream &os ,const line_message &t) {
    os<<"operation:"<<t.operation<<"; addr="<<hex<<(t.address_l+(((uint64_t)t.address_h)<<32))
        <<"; size ="<<hex<<t.len<<"; id="<<hex<<t.id<<endl;
    return os;
}
} // namespace DDRSim